[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "a6328c3b0515adee0518cd8c5b67169f3e9064a9"
os = "macos"

    [[PMIx.download]]
    sha256 = "d17589efed695228ae8498fbbd3a882f3af25995956ed630cdbb01bafdf5484c"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.aarch64-apple-darwin.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "68ebbc66d50749b2aff6fd0eb32785adbc54fb94"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "21d3dd8e0b8acd953f7e32642fbf50edae4128cd7e8e4838947c80b9341bd85f"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.aarch64-linux-gnu.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "ec519a2fea2cdbe25a904202e8d7c65bc26aa51d"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "dc98ffabb4339a9da57962abc1d990c233c06bd129d8c2562990464976f4bdd0"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.aarch64-linux-musl.tar.gz"
[[PMIx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b44e5fdfe631c41f6fff0e175577d124d601708"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "91feda28fdc9d8311fd5a5ca0e68c41ac0c56bc25578572993b795efacbc0b88"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.armv6l-linux-gnueabihf.tar.gz"
[[PMIx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "27945417eaa5fd767d573b714ca0e3a7eb48e209"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "d7036b05e62347919a1159970ac28a06c6ff000f1f9a972e5c9854ff2929f5a4"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.armv6l-linux-musleabihf.tar.gz"
[[PMIx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "672694429b1f29bd591cdb42566efb1771e2d86f"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "057b464c2ec0b2f29c2a01bbf3ee9e73d83e47070fc04726b396df9befa940b0"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.armv7l-linux-gnueabihf.tar.gz"
[[PMIx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6815a975184dd5b5befad7158728889db4aaee0"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "af9eaeaf19c87a239a03a782f503ad5b1720e6349decbd578d31e76496351f87"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.armv7l-linux-musleabihf.tar.gz"
[[PMIx]]
arch = "i686"
git-tree-sha1 = "149f3cca6516e36729cd41dcd05c32f4af27c417"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "1667792323db749a3cf91c841d757c0b373c809ef76c0a897a479af1f4a62469"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.i686-linux-gnu.tar.gz"
[[PMIx]]
arch = "i686"
git-tree-sha1 = "cf891cc8d48ef487784ed3e44d0fc4641349a6fb"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "c7aea56ac2e3680771d41531fb1b550e768eba7bd7c1efe4b82795ff0ddb68e2"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.i686-linux-musl.tar.gz"
[[PMIx]]
arch = "powerpc64le"
git-tree-sha1 = "1e69e74a989f40b53e1048ffde43429588c2ff59"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "483c61037a0be629f6d60ead6111e4e9ad74a56230680aff92d2fc6cda18818e"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.powerpc64le-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "47a1551db4537e3d5759ce8aebf2f729b7cdda6f"
os = "macos"

    [[PMIx.download]]
    sha256 = "6e6778fabd8ff72e9092f26b59e9ff6f82368fff83f355070d65f453cdfe3dad"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.x86_64-apple-darwin.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "b64ad2ff5bdc8b41a59009d2b5547838cfde4f5d"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "cd815d3995b9615ddfbbf582ec88be73e74396a77f300e61910674e47c5c32d8"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.x86_64-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "1a1cce0dedce4e2ca218c3dc3483aa5f34d697af"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "f1e9eeab441f1d787d15044823d734f6052a77750f01fa5280adb9872f86eb26"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.7+0/PMIx.v4.2.7.x86_64-linux-musl.tar.gz"
