[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "e3bf714137cdb1d35f521c87af09d1ae1f888d21"
os = "macos"

    [[PMIx.download]]
    sha256 = "7d1c9e829a4872de3a81fd3a1958a2c6d3b0f5982798e8b72ce89387685c19e5"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v5.0.3+0/PMIx.v5.0.3.aarch64-apple-darwin.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "af55ef7870b0ee8f82b15004ed7a6d2dd8b854e5"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "042aeb1b6d1c03eb933d42f29791b228b5c14a676af4686e936185de4e2b101f"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v5.0.3+0/PMIx.v5.0.3.aarch64-linux-gnu.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "81318369c94293e1efd67f0e6e28142457d02661"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "0c1c36d5d6adbf4736d3ccf852c3ef0a5132f6927289cd675833c5fe52126782"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v5.0.3+0/PMIx.v5.0.3.aarch64-linux-musl.tar.gz"
[[PMIx]]
arch = "powerpc64le"
git-tree-sha1 = "c2285c1c3a9d8b4c82f43c7b69b06e6cd2435a95"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "edee24746dfefefad92625e930d58b647269780cd3df048711b0d2233a5dbbfb"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v5.0.3+0/PMIx.v5.0.3.powerpc64le-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "bc0ce062baa836341270ff749756cc6dce2e68e5"
os = "macos"

    [[PMIx.download]]
    sha256 = "76fa885c95972a3fbf17d6940aa659c7213d74f3e94d1641884934a055aafff9"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v5.0.3+0/PMIx.v5.0.3.x86_64-apple-darwin.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "dd08c1378e132c59b9d1e08988f3db39cbb0567c"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "0e0c89de96d153e1b40eef202189c6283b7c763fd541a29682894e293ed4394e"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v5.0.3+0/PMIx.v5.0.3.x86_64-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "ade90ca7a1e0fa430a482983a36e667cc4e40153"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "41de46ace994a41274600761922bb0f02cc40b107e3640afb1281f1fdddba2ce"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v5.0.3+0/PMIx.v5.0.3.x86_64-linux-musl.tar.gz"
