[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "8b60db34b6497e7437514f7471192cf65366e2c0"
os = "macos"

    [[PMIx.download]]
    sha256 = "8e46c435008da5c308baa6abffbb6e7b8c837c71ab78c9fa4fd0664ed23b4b57"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.aarch64-apple-darwin.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "76c3bbfdd131ceae1bd3e31266debc07cd0200e8"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "fc40c714159f687d17e2f25b0a5f695604b1b988290d15d5ab2bb8479f412161"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.aarch64-linux-gnu.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "3fb100f05fa337c62607966be34ec98a1cdf6a9f"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "35e47d661cdedbbc994391b9a5ffc638c8a2b68e87cb307a8fa7b7f5cbacc181"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.aarch64-linux-musl.tar.gz"
[[PMIx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8c2be5fef4c41581f93defb5494e4320fdc4ee8"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "32a0945d537e618e354595cdd30f5d5dceabed90c79f00026126d017bccda7e9"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.armv7l-linux-gnueabihf.tar.gz"
[[PMIx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e1badfbcdf041133ac4ba42f103655b60abab7d4"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "e649eaa660c1082176af949cdb04846f401afed0d62131644b2a863c4f2737c0"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.armv7l-linux-musleabihf.tar.gz"
[[PMIx]]
arch = "i686"
git-tree-sha1 = "b98f9caa608f6c827ce21369ba2e4e4b17b844bf"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "ad8e52f7e72481440b36b86c04664e1fb82ea4b428938b171582e9184c6427e3"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.i686-linux-gnu.tar.gz"
[[PMIx]]
arch = "i686"
git-tree-sha1 = "cdbe6ad65711d8b25d9636df8c3f4a7a10e1010b"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "503055cb8886822c4a1a44f60da5384bfab73555424653298bc75c61ddbe2f6f"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.i686-linux-musl.tar.gz"
[[PMIx]]
arch = "powerpc64le"
git-tree-sha1 = "aea0989f24fc0202fd2a3536871f4e9a7a381def"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "801e429418546675ae4979a326888c849eec026e3eefe0542d56d856fb4e4306"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.powerpc64le-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "a3ec8162df908d9b3398dc0c7d067d9e54b625cd"
os = "macos"

    [[PMIx.download]]
    sha256 = "903fcb80f639ac68cdb1deffcdfd78a64a9650e46917ea955067be0169cf25e8"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.x86_64-apple-darwin.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "6a24a9c1e3422a080cada7b76884230106316952"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "83d5bc91bac92892ea0b4613130df480dd360e4dffd990c2e09de413550e5ad0"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.x86_64-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "a4ab4b600b0f000a7e88d54e03c0b7ff003b371a"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "411e48e4b803f7f97e1a94df54433d1fd1699c5e6273787279a3a6cc13325398"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+2/PMIx.v4.1.0.x86_64-linux-musl.tar.gz"
