[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "1a643ebca72c13e7ed2f700e10deb4b04224a792"
os = "macos"

    [[PMIx.download]]
    sha256 = "1e1e3ad0952166cc113ac4a5459f2e0cb53e55d3b27798f463986dbe40ecd5ca"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.aarch64-apple-darwin.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "72c2a73b7aa3b14117ba4e4a947be449ca6824d3"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "44b423aab9bee721457876d3212b1ac568d23c49c108c51320acb502c9ae08e6"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.aarch64-linux-gnu.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "c8e4f2ed67d36c20ab952d437910adbe2963c705"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "14b1cbbc5f81f6dd2151e4266d45c635af2e2266bb0c7378a8ea21004f6de4a9"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.aarch64-linux-musl.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "751606530104894d866f3700d35c38accf37a836"
os = "freebsd"

    [[PMIx.download]]
    sha256 = "abccc240cc31e81e909d561bdf644001d0c42f839b88112b0e56995dc487765a"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.aarch64-unknown-freebsd.tar.gz"
[[PMIx]]
arch = "powerpc64le"
git-tree-sha1 = "a1e30c78acf9e3834b352d5224e7c69b82a3c1d8"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "456346f24ddd0eab287c2c46e30767ed7021d4493a49a8cb193250e7f15017f7"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.powerpc64le-linux-gnu.tar.gz"
[[PMIx]]
arch = "riscv64"
git-tree-sha1 = "4199367c48b508e518aa6906a74335483d419649"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "60e5fd8d8ba8ef8142be4c6e337ef61387f5e2e2aa589dc65dd286d370b00869"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.riscv64-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "6ee382faa81358ea4b147028ee49db95ff06a132"
os = "macos"

    [[PMIx.download]]
    sha256 = "f37a315fe4ca074d42673ce33e02800cd7f39805356745b0cd6ebd22f49af685"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.x86_64-apple-darwin.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "149be2b04d93b2f05828d31d43450fc327d5457d"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "199caa17c568a0040995fd6dad0695e2de0563d188d94f28bf016e3a82acde19"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.x86_64-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "0d9fb42cd9290513da8e24b452bbe83ad7b94d71"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "c6dd6b571be4ee2963e91d453acd4b7e33c5f8e7a3062217e439657e22ea0f18"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.x86_64-linux-musl.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "a3924f8b796738fc4055ff9f54c83f01ab9a8334"
os = "freebsd"

    [[PMIx.download]]
    sha256 = "d5a34678881b2528f905ff634a1213a2e92e3651967e8e037b9d171c881b182c"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v6.1.0+0/PMIx.v6.1.0.x86_64-unknown-freebsd.tar.gz"
