[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "724a46726fefd8fc9f084d05fd4b115da5ee5953"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "b43c7199bb893cef62a9b4f052aeb70cad5db8cf82e527c66e7eef835c5ab945"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.aarch64-linux-gnu.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "425dfe840fd60db11fc04154abd8af7831216912"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "720e94ee17d587fdf4cce022eaf2ec67c5a07d11dad14fadffa7405c7c32efa9"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.aarch64-linux-musl.tar.gz"
[[PMIx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e3d6484edd0a4a255bb11d29fd22535871c0f3c7"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "39b649e2a7c3c6fafe755cac9e864b5871e64154eeb7bc3da3e2930a6423541a"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.armv7l-linux-gnueabihf.tar.gz"
[[PMIx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb807d5cfdeaac2b925fbadaa563b49f338ab6cf"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "8754291f2c9506260a37ff4b6c5d6c4cea660a646c4e1615a85c49660e9611ca"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.armv7l-linux-musleabihf.tar.gz"
[[PMIx]]
arch = "i686"
git-tree-sha1 = "5429d3016b7cd4592a3b5b84844182b78f216669"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "c71a74381ca65eb473f2a383f4531421f8177d5a58cb71c9a231834b6d357ceb"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.i686-linux-gnu.tar.gz"
[[PMIx]]
arch = "i686"
git-tree-sha1 = "4f89694e0fa543b66b12e5e37201fc3e9de391e1"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "c0611618f36425302612c2bdd4f02912671007b887a613d2d9f5e21ca14acbd5"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.i686-linux-musl.tar.gz"
[[PMIx]]
arch = "powerpc64le"
git-tree-sha1 = "ae35223ca548dc91c2facdbfbc1d0ce901ba3716"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "dbbf7ac42f31d2fccd806eeb1d06e647a08866c5c17b226c0ea09af6194434ce"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.powerpc64le-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "cb155e272fdb58caa077ae2c7ba8b3a08f4d7b25"
os = "macos"

    [[PMIx.download]]
    sha256 = "7e7ae2cd8124d37bc8cf4d49ea419e4281a261d600c74b15439fae30efe73ce7"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.x86_64-apple-darwin.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "2c9e5ebd74d889466a7d84727c93aa2ac712c58b"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "04b8b63e0620541fb65c197f2e3d6e24ba1d36f88cd4cf8ddc276e9b6d69c7ef"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.x86_64-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "15a7edbbea2b4112b4b337e27e8a68a76e9b8d35"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "ab2b4ff7297b7222f8cecf2eb2d9a133af2885a9b37e82819450bfad7a46f69a"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+0/PMIx.v4.1.0.x86_64-linux-musl.tar.gz"
