[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "d2bc4f68b5e015d0d5a6b64adb9835716daf6bb3"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "db0dcaf266eaa464795a158a06b76509a599fd1ea6c7501d44eeb50a3cd748bd"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.aarch64-linux-gnu.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "a65aa157a7d81d03712c6432e952128039246290"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "7886bab502823dd4bebbf8ce65cd3de7a8e27068130471725790949674b531f5"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.aarch64-linux-musl.tar.gz"
[[PMIx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40f7fdba22dcd391b90a7360192b69ec020a15e6"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "8f6964aa0405536da6d1410621b37022a2fdd5a1a650a036a29a79eb12e6ec2a"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.armv7l-linux-gnueabihf.tar.gz"
[[PMIx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d70966046b3a17a362a3fcc260a856ef8cf5a8fc"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "9099f081c32332667f41e654153f8b9ad405aaf79dc58ba263cacee3d0b7d546"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.armv7l-linux-musleabihf.tar.gz"
[[PMIx]]
arch = "i686"
git-tree-sha1 = "c59a5219cd63f3b287208727605b67cef1c9a260"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "326f39a4b6500b73705c508a6c49480d6b34cbc4b2d31896cb91d1958b0fd5d3"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.i686-linux-gnu.tar.gz"
[[PMIx]]
arch = "i686"
git-tree-sha1 = "e28c6f5a9db2eeac317cd421f4e474b164dc8048"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "0ba83dc23d5fc4f63ca6c1150d424b7ae82b4c6c055d75e8f2eedbb25ad8db41"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.i686-linux-musl.tar.gz"
[[PMIx]]
arch = "powerpc64le"
git-tree-sha1 = "c7bed5411b08b44fa0518ae303239df8f5d8fdb0"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "ac7bc47257b17de749cfe4501c3e06150ffccc66c1f914db315595c025e098d1"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.powerpc64le-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "c244e787bc57eef0794b055c3067fec986416d00"
os = "macos"

    [[PMIx.download]]
    sha256 = "8bf86b179f46b8d2913c4591c9265c183b76bbb3223585a48b0a0769a58ef7fd"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.x86_64-apple-darwin.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "876cea3383fd6a4ae399e14918fe9fbcd7ce9bdd"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "64fa02a45f841b026ba64ea42c9a750a7c2f991cd00e691e16e8a1d74c76bb0a"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.x86_64-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "2d7a8af99499cee14cf7500a8d73b2f37675e02d"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "3e9a041f3cf7409cedae70ee0b764fb67a36e0b49b36de69f91a6dec2a1514db"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.1.0+1/PMIx.v4.1.0.x86_64-linux-musl.tar.gz"
