[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "5e663b47d79ac9bd0a3044f171edf4f1f35f205f"
os = "macos"

    [[PMIx.download]]
    sha256 = "792a9bb895b638ca3c4efc674be822b1312252d75c02113b505bd9205e1d980c"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.9+0/PMIx.v4.2.9.aarch64-apple-darwin.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "5d2ee500210ee88c0ab67ac851a749b695b9c39a"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "983a62d3aa52b215de6ac5b381dc890c7d5784706f64211bb838379317113049"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.9+0/PMIx.v4.2.9.aarch64-linux-gnu.tar.gz"
[[PMIx]]
arch = "aarch64"
git-tree-sha1 = "700d9df957ba15d4030afa230111e91680277466"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "97b4ca08e12f25eef194db135da4da5a17739b105c8a2800f817b531126a05f6"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.9+0/PMIx.v4.2.9.aarch64-linux-musl.tar.gz"
[[PMIx]]
arch = "powerpc64le"
git-tree-sha1 = "fe2375c4177742d72a4d2f73ac67b5153bf9eaf6"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "931f33d6062a9fb05c7a250289462ba307b04fb5fb0d96809b1b6ca9580496fd"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.9+0/PMIx.v4.2.9.powerpc64le-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "0580cc81ecd648fb6bf346a17ea3f27db42f0755"
os = "macos"

    [[PMIx.download]]
    sha256 = "e8629c895c93df8829c4518e8c0e4d3fc840c55213862e505d841e310c927946"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.9+0/PMIx.v4.2.9.x86_64-apple-darwin.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "9b346e17369f84b6deab24975d2c344f4bcf5bf4"
libc = "glibc"
os = "linux"

    [[PMIx.download]]
    sha256 = "01b451091b669242aea461aecc372b1d1909d13b2487728e6119cececdf0f27a"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.9+0/PMIx.v4.2.9.x86_64-linux-gnu.tar.gz"
[[PMIx]]
arch = "x86_64"
git-tree-sha1 = "01fb25db6af3100f6a88033c4a5980dc5fbea037"
libc = "musl"
os = "linux"

    [[PMIx.download]]
    sha256 = "d7c1416c7b3531e156a990292f463a08dcc78d419ecc96291eb881196ad19313"
    url = "https://github.com/JuliaBinaryWrappers/PMIx_jll.jl/releases/download/PMIx-v4.2.9+0/PMIx.v4.2.9.x86_64-linux-musl.tar.gz"
